### ISSUE TITLE
Parse forwarded donation emails

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#11]
• ACLU
• Planned Parenthood
• Doctors without Borders

Add to database, and send email to campaigner.

- [ ] tests

**Comment by j6k4m8** [comment]
Need to:

• detect class of email
• send it to the correct parser
• record those choices in the record of the email in dynamo (plus a pointer
to the original file and its expiry)

**Comment by slavingia** [comment]
we will be able to infer the class of email from the email they're forwarding to, as each match campaign is linked to a charity, right?

**Comment by slavingia** [comment]
also, standardize the match email. i'm not sure if we've decided but match-{id} or something is my preference. i wanted it to be more verbose initially but with such a long id, it looks kinda strange and messes w the simple ui w/ short width.

**Comment by slavingia** [comment]
this is done now @j6k4m8 ?

**Comment by j6k4m8** [comment]
"done" for `ACLU` — writing `MSF` (and rewriting ACLU) tonight to use BeautifulSoup as a more robust parser

**Comment by j6k4m8** [comment]
Tests in #46 — then this is done!
