### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by j6k4m8** [donatemates/donatemates#14]
Relevant to #10: We'll want it to be clear what should and should not be in scope for public pull-requests.

**Comment by slavingia** [comment]
i think we can use this: https://github.com/blog/2111-issue-and-pull-request-templates

thoughts? there's some room to go before we can have this easily worked on (a local.host version of the AWS stack is needed otherwise we're gonna have to manually onboard people).

**Comment by slavingia** [comment]
addressed by #48
