### ISSUE TITLE
Add "cancel" campaign link to intro email

### ISSUE THREAD

**Issue by dkleissa** [donatemates/donatemates#17]
In original email sent to the campaigner, have a button/link that can cancel a campaign

- [x] Update intro email to include link
- [x] Add `DELETE` method to `campaign/`
- [x] Add frontend to confirm cancellation and call API

**Comment by dkleissa** [comment]
@slavingia - Added a new API endpoint and updated the intro email. Now it assumes there will be a page to "confirm" the user wants to cancel their campaign that needs to be created. If they do confirm, you need to make an API call to actually delete the campaign.

Expected page: https://donatemates.com/cancel.html?id=<campaign_id>&secret=<secret_key>

API Call: DELETE https://api.donatemates.com/campaign/<campaign_id>/<secret_key>

Work committed to branch "cancel-campaign"

**Comment by slavingia** [comment]
thank you. i'll do this tmmrw.
