### ISSUE TITLE
404 pages

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#19]
- [x] 404 pages for wrong charity id
- [x] 404 pages for other URLs

**Comment by slavingia** [comment]
@dkleissa i can tackle the wrong charity id in the front end, but the other URLs are on you!

**Comment by slavingia** [comment]
if you go to donatemates.com/asiodfahsdfioasdf redirect to 404.html (pushing to `sahil-integration` now).

**Comment by dkleissa** [comment]
S3 throws a 403 when you try to route to a file that doesn't exist. Since we have no "auth" that would return at 403 for real, CloudFront now catches all 403's, routes to the /404.html page, and changes the status code to be 404.
