### ISSUE TITLE
Analytics API

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#24]
A simple route to monitor how we're doing :)

- [x] total $ donated
- [x] total # of donations
- [x] total # of campaigns

at some point (once it's impressive) we could make the homepage include total $ donated.

**Comment by dkleissa** [comment]
@slavingia - What do you think about this:

`/stats` - returns all the stats we compute globally for the whole site
`/stats/<campaign_id>` - returns all the stats we can compute for a single campaign

**Comment by slavingia** [comment]
works great for me!

**Comment by dkleissa** [comment]
realized that /stats/<campaign_id> probably doesn't make sense for now, since the `/campaign` endpoint already returns what you would want to show for an individual campaign. 

Added a `/stats/` endpoint for site wide stats in #54
