### ISSUE TITLE
Lightweight backend app (flask?)

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#27]
- [x] donatemates.com/campaign/{id}
- [x] donatemates.com/campaign/{id}/cancel
- [x] 404s served by backend (404.html)
- [ ] DRY `<head>` and layout

**Comment by dkleissa** [comment]
Currently the way things are set up, we cannot do a re-write of the URL and still have an SSL cert. If we host directly out of S3 instead of using CloudFront we can re-write the URL. Recommend deferring this until lambda@edge is GA or we add a full backend. Since Twitter will auto shorten the URL anyway, doesn't seem like a big deal at the moment.

**Comment by slavingia** [comment]
what's GA?

**Comment by slavingia** [comment]
fwiw, twitter i believe unshortens the URL to show the full one in native apps. not 100% sure though. but yea, we can do this after MVP is live.

**Comment by slavingia** [comment]
imo the right solution is an ultra leightweight flask app then, to serve the campaign pages w/ preloaded data from prettier URLs, then the JS can just keep the numbers updated every 10 seconds.

**Comment by dkleissa** [comment]
Sorry. GA = Generally Available

Yeah seems reasonable. We can revisit in a little bit.

**Comment by slavingia** [comment]
noting here since it'll solve this too:

- [ ] and lay the groundwork for some DRY code cleanup using HTML templates.

**Comment by slavingia** [comment]
we can also consider using webpack if you think that's a better fit? whatever you prefer.

**Comment by dkleissa** [comment]
@slavingia - What did you have in mind for the `DRY <head> and layout` task? We've refactored things to use React and added some clever re-writing with Lambda@Edge so everything is statically hosted out of CloudFront. Think we're pretty close here.

**Comment by slavingia** [comment]
awesome. just to save some codespace on these bits:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">
    <title>Donatemates</title>
    <meta name="description" content="Automated matching made easy." />
    <link rel="stylesheet" href="style.css" />
    <link rel="icon" type="image/png" href="icon.png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <meta name="twitter:card" value="summary">
    <meta name="twitter:site" content="@donatemates">

    <meta property="og:title" content="Donatemates" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="https://donatemates.com/" />
    <meta property="og:image" content="https://donatemates.com/icon.png" />
    <meta property="og:description" content="Automated matching made easy." />
  </head>
  <body>
    <div class="wrapper">
ONLY THING THAT CHANGES
    </div>
    <script>window.twttr = (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
      if (d.getElementById(id)) return t;
      js = d.createElement(s);
      js.id = id;
      js.src = "https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);

      t._e = [];
      t.ready = function(f) {
        t._e.push(f);
      };

      return t;
    }(document, "script", "twitter-wjs"));</script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-92313343-1', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>
```

**Comment by dkleissa** [comment]
ok so then a question for @j6k4m8 - this might have been cleaned up already with React?

**Comment by j6k4m8** [comment]
Resolved via React :)
