### ISSUE TITLE
API for front-end

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#3]
(api.donatemates.com)

- [x] Service to `POST` *new* campaigns
- [x] Service to `GET` a campaign's properties in JSON format on load and every minute
- [x] Service to `GET` list of supported charities in JSON format
- [x] Add donation calculation via querying DB

**Comment by dkleissa** [comment]
Initial API is ready for integration with frontend and tweaks as needed. Unit and integration tests are complete.
