### ISSUE TITLE
Make lambda handler robust to lambda failure reinvocations

### ISSUE THREAD

**Issue by dkleissa** [donatemates/donatemates#31]
This shouldn't be a big problem when things are 100% working, but if lambda invocations fail and a message gets automatically retried, need to be careful not to continually notify the user and record duplicate donations.

**Comment by dkleissa** [comment]
currently guarding against processing receipts sent multiple times, so this protects a campaign from getting inflated due to re-processed emails on an invocation error/retry (which typically shouldn't happen). The sender may get duplicate email alerts that we could not process their receipt though. I feel this is adequate for now.

**Comment by slavingia** [comment]
agreed, that is a solid solution
