### ISSUE TITLE
Better copy in campaign update emails

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#40]
I started on this in `copytweaks`. @dkleissa can you look at the branch and fill in the

```
donation_total_cents = ...
```

bit? and then this PR should be good to go.

**Comment by dkleissa** [comment]
You had it mostly there. Made some final tweaks and will PR this in now. You are OK with no HTML emails for now, and we'll add later I'm assuming? Also we'll probably eventually need to add an unsubscribe link, terms, and a little more to make it clear its from donatemates.
