### ISSUE TITLE
1-line CLI deploy

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#5]
- [x] disable swagger docs on production stack
- [x] add confirmation on create
- [x] add command to update frontend only
- [x] refactor lambda code for processing emails
- [x] add data for the populate command
- [x] add ~~jordan~~, ~~sahil~~, and prod stacks to environment and config
- [x] add SES automation
- [x] update zappa policy to allow sending emails from lambda
- [x] get out of the SES sandbox
- [x] Add bounce and complaint SES topics to production

**Comment by dkleissa** [comment]
@j6k4m8 - I think by default SES will actually autoforward bounces and complaints to the admin email address if I do nothing. Ok with this, since it'll hit your email? Can also setup SNS topics instead.

**Comment by j6k4m8** [comment]
Totally fine — already have an Inbox rule set up :)
