### ISSUE TITLE
LESS or SCSS

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#6]

**Comment by j6k4m8** [comment]
Is there a client-side-only SCSS parser? or does this build before we bundle?

(don't want to keep suggesting new techs, but LESS's js parser is pretty snazzy!)

**Comment by slavingia** [comment]
i think a friend said GULP would do that

**Comment by j6k4m8** [comment]
Between gulp and webpack I think I'd vote for webpack — have been having
really good experiences with it recently. If you're up in the air, webpack
vote from me! Otherwise gulp is a great tool as well.

**Comment by slavingia** [comment]
yea, either works for me. also, i don't know why i added this to the mvp. this can happen after launch. i just know a front-end developer/designer will want to spice things up here, so added early.

also, @aaronrelph expressed interest in doing this.

**Comment by j6k4m8** [comment]
Resolved in #70!
