### ISSUE TITLE
Charity table

### ISSUE THREAD

**Issue by slavingia** [donatemates/donatemates#7]
• id
• name (e.g. "ACLU", "Planned Parenthood")
• conversationalName (e.g. "the ACLU", "Planned Parenthood")

And potentially other things the lambda file could use to DRY code?

**Comment by dkleissa** [comment]
Implemented this as a dictionary that is loaded by both the API and lambda function for now. Dictionary stores the `name`, `conversational_name`, and `class` to load for parsing. API only returns the `name` and `conversational_name`.
